/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PatientPrescriptionRouteImport } from './routes/patient/prescription'
import { Route as PatientMedicationRouteImport } from './routes/patient/medication'
import { Route as PatientAppointmentsRouteImport } from './routes/patient/appointments'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPatientsRouteImport } from './routes/admin/patients'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminAppointmentRouteImport } from './routes/admin/appointment'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PatientPrescriptionRoute = PatientPrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientMedicationRoute = PatientMedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppointmentRoute = AdminAppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRoute
  '/admin/appointment': typeof AdminAppointmentRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/users': typeof AdminUsersRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/medication': typeof PatientMedicationRoute
  '/patient/prescription': typeof PatientPrescriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRoute
  '/admin/appointment': typeof AdminAppointmentRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/users': typeof AdminUsersRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/medication': typeof PatientMedicationRoute
  '/patient/prescription': typeof PatientPrescriptionRoute
  '/admin': typeof AdminIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRoute
  '/admin/appointment': typeof AdminAppointmentRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/users': typeof AdminUsersRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/medication': typeof PatientMedicationRoute
  '/patient/prescription': typeof PatientPrescriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/patient'
    | '/about'
    | '/doctors'
    | '/login'
    | '/programs'
    | '/services'
    | '/admin/appointment'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/users'
    | '/patient/appointments'
    | '/patient/medication'
    | '/patient/prescription'
    | '/admin/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/doctors'
    | '/login'
    | '/programs'
    | '/services'
    | '/admin/appointment'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/users'
    | '/patient/appointments'
    | '/patient/medication'
    | '/patient/prescription'
    | '/admin'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/patient'
    | '/about'
    | '/doctors'
    | '/login'
    | '/programs'
    | '/services'
    | '/admin/appointment'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/users'
    | '/patient/appointments'
    | '/patient/medication'
    | '/patient/prescription'
    | '/admin/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PatientRouteRoute: typeof PatientRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DoctorsRoute: typeof DoctorsRoute
  LoginRoute: typeof LoginRoute
  ProgramsRoute: typeof ProgramsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/patient/prescription': {
      id: '/patient/prescription'
      path: '/prescription'
      fullPath: '/patient/prescription'
      preLoaderRoute: typeof PatientPrescriptionRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/medication': {
      id: '/patient/medication'
      path: '/medication'
      fullPath: '/patient/medication'
      preLoaderRoute: typeof PatientMedicationRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointment': {
      id: '/admin/appointment'
      path: '/appointment'
      fullPath: '/admin/appointment'
      preLoaderRoute: typeof AdminAppointmentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAppointmentRoute: typeof AdminAppointmentRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAppointmentRoute: AdminAppointmentRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PatientRouteRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientMedicationRoute: typeof PatientMedicationRoute
  PatientPrescriptionRoute: typeof PatientPrescriptionRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteRouteChildren: PatientRouteRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientMedicationRoute: PatientMedicationRoute,
  PatientPrescriptionRoute: PatientPrescriptionRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DoctorsRoute: DoctorsRoute,
  LoginRoute: LoginRoute,
  ProgramsRoute: ProgramsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
