/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as PageRouteImport } from './routes/page'
import { Route as OtpVerificationRouteImport } from './routes/otp-verification'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PaymentsSuccessRouteImport } from './routes/payments.success'
import { Route as PatientProfileRouteImport } from './routes/patient/profile'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient/prescriptions'
import { Route as PatientPaymentsRouteImport } from './routes/patient/payments'
import { Route as PatientMedicationRouteImport } from './routes/patient/medication'
import { Route as PatientMedicalHistoryRouteImport } from './routes/patient/medical-history'
import { Route as PatientDoctorsRouteImport } from './routes/patient/doctors'
import { Route as PatientChatRouteImport } from './routes/patient/chat'
import { Route as PatientAppointmentsRouteImport } from './routes/patient/appointments'
import { Route as DoctorSettingRouteImport } from './routes/doctor/setting'
import { Route as DoctorProfileRouteImport } from './routes/doctor/profile'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor/prescriptions'
import { Route as DoctorPatientsRouteImport } from './routes/doctor/patients'
import { Route as DoctorMedicalHistoryRouteImport } from './routes/doctor/medical-history'
import { Route as DoctorChatRouteImport } from './routes/doctor/chat'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor/appointments'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPrescriptionsRouteImport } from './routes/admin/prescriptions'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPatientsRouteImport } from './routes/admin/patients'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMedicationsRouteImport } from './routes/admin/medications'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpVerificationRoute = OtpVerificationRouteImport.update({
  id: '/otp-verification',
  path: '/otp-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRouteRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PaymentsSuccessRoute = PaymentsSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientPaymentsRoute = PatientPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientMedicationRoute = PatientMedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientMedicalHistoryRoute = PatientMedicalHistoryRouteImport.update({
  id: '/medical-history',
  path: '/medical-history',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientDoctorsRoute = PatientDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientChatRoute = PatientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRouteRoute,
} as any)
const DoctorSettingRoute = DoctorSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorMedicalHistoryRoute = DoctorMedicalHistoryRouteImport.update({
  id: '/medical-history',
  path: '/medical-history',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorChatRoute = DoctorChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPrescriptionsRoute = AdminPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMedicationsRoute = AdminMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/chats': typeof ChatsRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/page': typeof PageRoute
  '/password-reset': typeof PasswordResetRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/medications': typeof AdminMedicationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/chat': typeof DoctorChatRoute
  '/doctor/medical-history': typeof DoctorMedicalHistoryRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/setting': typeof DoctorSettingRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/medical-history': typeof PatientMedicalHistoryRoute
  '/patient/medication': typeof PatientMedicationRoute
  '/patient/payments': typeof PatientPaymentsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/chats': typeof ChatsRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/page': typeof PageRoute
  '/password-reset': typeof PasswordResetRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/medications': typeof AdminMedicationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/chat': typeof DoctorChatRoute
  '/doctor/medical-history': typeof DoctorMedicalHistoryRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/setting': typeof DoctorSettingRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/medical-history': typeof PatientMedicalHistoryRoute
  '/patient/medication': typeof PatientMedicationRoute
  '/patient/payments': typeof PatientPaymentsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/chats': typeof ChatsRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/page': typeof PageRoute
  '/password-reset': typeof PasswordResetRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/medications': typeof AdminMedicationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/chat': typeof DoctorChatRoute
  '/doctor/medical-history': typeof DoctorMedicalHistoryRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/setting': typeof DoctorSettingRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/medical-history': typeof PatientMedicalHistoryRoute
  '/patient/medication': typeof PatientMedicationRoute
  '/patient/payments': typeof PatientPaymentsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/about'
    | '/chat'
    | '/chats'
    | '/doctors'
    | '/login'
    | '/otp-verification'
    | '/page'
    | '/password-reset'
    | '/programs'
    | '/register'
    | '/services'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/medications'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/prescriptions'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/chat'
    | '/doctor/medical-history'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/setting'
    | '/patient/appointments'
    | '/patient/chat'
    | '/patient/doctors'
    | '/patient/medical-history'
    | '/patient/medication'
    | '/patient/payments'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/payments/success'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/chats'
    | '/doctors'
    | '/login'
    | '/otp-verification'
    | '/page'
    | '/password-reset'
    | '/programs'
    | '/register'
    | '/services'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/medications'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/prescriptions'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/chat'
    | '/doctor/medical-history'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/setting'
    | '/patient/appointments'
    | '/patient/chat'
    | '/patient/doctors'
    | '/patient/medical-history'
    | '/patient/medication'
    | '/patient/payments'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/payments/success'
    | '/admin'
    | '/doctor'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/about'
    | '/chat'
    | '/chats'
    | '/doctors'
    | '/login'
    | '/otp-verification'
    | '/page'
    | '/password-reset'
    | '/programs'
    | '/register'
    | '/services'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/medications'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/prescriptions'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/chat'
    | '/doctor/medical-history'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/setting'
    | '/patient/appointments'
    | '/patient/chat'
    | '/patient/doctors'
    | '/patient/medical-history'
    | '/patient/medication'
    | '/patient/payments'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/payments/success'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DoctorRouteRoute: typeof DoctorRouteRouteWithChildren
  PatientRouteRoute: typeof PatientRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  ChatsRoute: typeof ChatsRoute
  DoctorsRoute: typeof DoctorsRoute
  LoginRoute: typeof LoginRoute
  OtpVerificationRoute: typeof OtpVerificationRoute
  PageRoute: typeof PageRoute
  PasswordResetRoute: typeof PasswordResetRoute
  ProgramsRoute: typeof ProgramsRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  PaymentsSuccessRoute: typeof PaymentsSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp-verification': {
      id: '/otp-verification'
      path: '/otp-verification'
      fullPath: '/otp-verification'
      preLoaderRoute: typeof OtpVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof PaymentsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/payments': {
      id: '/patient/payments'
      path: '/payments'
      fullPath: '/patient/payments'
      preLoaderRoute: typeof PatientPaymentsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/medication': {
      id: '/patient/medication'
      path: '/medication'
      fullPath: '/patient/medication'
      preLoaderRoute: typeof PatientMedicationRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/medical-history': {
      id: '/patient/medical-history'
      path: '/medical-history'
      fullPath: '/patient/medical-history'
      preLoaderRoute: typeof PatientMedicalHistoryRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/doctors': {
      id: '/patient/doctors'
      path: '/doctors'
      fullPath: '/patient/doctors'
      preLoaderRoute: typeof PatientDoctorsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/chat': {
      id: '/patient/chat'
      path: '/chat'
      fullPath: '/patient/chat'
      preLoaderRoute: typeof PatientChatRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/doctor/setting': {
      id: '/doctor/setting'
      path: '/setting'
      fullPath: '/doctor/setting'
      preLoaderRoute: typeof DoctorSettingRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/medical-history': {
      id: '/doctor/medical-history'
      path: '/medical-history'
      fullPath: '/doctor/medical-history'
      preLoaderRoute: typeof DoctorMedicalHistoryRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/chat': {
      id: '/doctor/chat'
      path: '/chat'
      fullPath: '/doctor/chat'
      preLoaderRoute: typeof DoctorChatRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/prescriptions': {
      id: '/admin/prescriptions'
      path: '/prescriptions'
      fullPath: '/admin/prescriptions'
      preLoaderRoute: typeof AdminPrescriptionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/medications': {
      id: '/admin/medications'
      path: '/medications'
      fullPath: '/admin/medications'
      preLoaderRoute: typeof AdminMedicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminMedicationsRoute: typeof AdminMedicationsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPrescriptionsRoute: typeof AdminPrescriptionsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminMedicationsRoute: AdminMedicationsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPrescriptionsRoute: AdminPrescriptionsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DoctorRouteRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorChatRoute: typeof DoctorChatRoute
  DoctorMedicalHistoryRoute: typeof DoctorMedicalHistoryRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorSettingRoute: typeof DoctorSettingRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteRouteChildren: DoctorRouteRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorChatRoute: DoctorChatRoute,
  DoctorMedicalHistoryRoute: DoctorMedicalHistoryRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorSettingRoute: DoctorSettingRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

interface PatientRouteRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientChatRoute: typeof PatientChatRoute
  PatientDoctorsRoute: typeof PatientDoctorsRoute
  PatientMedicalHistoryRoute: typeof PatientMedicalHistoryRoute
  PatientMedicationRoute: typeof PatientMedicationRoute
  PatientPaymentsRoute: typeof PatientPaymentsRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteRouteChildren: PatientRouteRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientChatRoute: PatientChatRoute,
  PatientDoctorsRoute: PatientDoctorsRoute,
  PatientMedicalHistoryRoute: PatientMedicalHistoryRoute,
  PatientMedicationRoute: PatientMedicationRoute,
  PatientPaymentsRoute: PatientPaymentsRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  ChatsRoute: ChatsRoute,
  DoctorsRoute: DoctorsRoute,
  LoginRoute: LoginRoute,
  OtpVerificationRoute: OtpVerificationRoute,
  PageRoute: PageRoute,
  PasswordResetRoute: PasswordResetRoute,
  ProgramsRoute: ProgramsRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  PaymentsSuccessRoute: PaymentsSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
